### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by Legends-of-NGDB** [VendroidEnhanced/Vendroid#100]
### Discord account

n/a

### What happens when the bug or crash occurs?

The app profile isn't normal. It is gay and it isn't pride month. How do I update the app?

### What is the expected behaviour?

.

### How do you recreate this bug or crash?

...

### Request agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [x] I have read the requirements for opening an issue above

**Comment by Legends-of-NGDB** [comment]
![Image](https://github.com/user-attachments/assets/cb3ee87f-d080-400c-b391-df6a1c32f86b)
Tried editing it but apk editor won't let me

**Comment by Legends-of-NGDB** [comment]
Pleaseee I don't wanna be gay 😭😭😭

**Comment by nin0-dev** [comment]
also sorry to tell you but i have sent homosexuality to you. you cannot escape the gay 🏳️‍🌈🏳️‍🌈🏳️‍🌈
