### ISSUE TITLE
[Bug] Text box doesn't register properly if backspacing too far 

### ISSUE THREAD

**Issue by ToasterCoaster5** [VendroidEnhanced/Vendroid#16]
### Discord account

toastercoaster5#0

### What happens when the bug or crash occurs?

Holding the backspace button to delete your whole message (perhaps deleting a 'character' that processes the text) appears to cause error upon typing again.

### What is the expected behaviour?

Unmodified mobile web client allows normal typing, whereas VendroidEnhanced will receive input after typing but not light up the blue 'Send' icon. Pressing Enter or Backspace registers the text again, but it all appears backwards.

![Screenshot_20240521-202228](https://github.com/VendroidEnhanced/Vendroid/assets/113394952/4b60af0a-ee89-4d1f-807f-95ccc358cec6)
![Screenshot_20240521-202248](https://github.com/VendroidEnhanced/Vendroid/assets/113394952/b1113643-f063-4c40-a622-c217e90c05e6)

### How do you recreate this bug or crash?

Type shit
Backspace until it's all deleted (it appears to delete a extra invisible character)
Try typing afterwards, see the still-gray send icon and the "Message channel" message in text box background 
Press Backspace or Enter, notice as Send icon turns blue, text box background is empty and all text is backwards inside

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
this was fixed by discord, seems like they added slash commands to mobile web

could you test right now

**Comment by nin0-dev** [comment]
okay ignore what i just said im soo stupit
