### ISSUE TITLE
[Bug] Vencord Category of Settings Missing

### ISSUE THREAD

**Issue by ToasterCoaster5** [VendroidEnhanced/Vendroid#18]
> [!WARNING]
> This issue is **known** and will soon be fixed. **DO NOT** OPEN any other issues about that or comment about being affected

### Discord account

toastercoaster5

### What happens when the bug or crash occurs?

The Vencord settings category simply... Isn't present. It was there before but I can't recall when it disappeared.

(The screenshot with the category of settings is from base Vendroid)
![Screenshot_20240529-133004](https://github.com/VendroidEnhanced/Vendroid/assets/113394952/6a06e5d5-8cfe-41e7-9209-74aad1ee73c4)
![Screenshot_20240529-133007](https://github.com/VendroidEnhanced/Vendroid/assets/113394952/b76cd4e8-7bfa-4293-a3b4-25136b03556e)

### What is the expected behaviour?

The settings should exist 

### How do you recreate this bug or crash?

Ion know 

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
send a screenshot of your version info

**Comment by Moodzz1** [comment]
I get this same issue
![Screenshot_2024-06-04-11-33-50-43_56bbc8167d0257d23a3582ded8ebec64](https://github.com/VendroidEnhanced/Vendroid/assets/88912716/5a986789-6b5e-46af-b2d1-9120e0699fe8)

**Comment by nin0-dev** [comment]
> I get this same issue ![Screenshot_2024-06-04-11-33-50-43_56bbc8167d0257d23a3582ded8ebec64](https://private-user-images.githubusercontent.com/88912716/336414389-5a986789-6b5e-46af-b2d1-9120e0699fe8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTc2OTgsIm5iZiI6MTcxNzQ5NzM5OCwicGF0aCI6Ii84ODkxMjcxNi8zMzY0MTQzODktNWE5ODY3ODktNmI1ZS00NmFmLWIyZDEtOTEyMGUwNjk5ZmU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEwMzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZGZmNjQ4Njk5MTc3MzYzMGRiZDg0ZjlhNGZkMGNlMDVmMzRlODk3ZjcxZWMyMmRkMWYyMGFjMGY0ZjM1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SsX5A6IQ0_v2wKFEsSeIiaDvNUpEudOH4UBzlogQ_78)

use stable

**Comment by nin0-dev** [comment]
so

- vendroid is stuck on an old vencord version with broken settings 
- which prevents vendroid settings from showing
- which prevents updating.

I'll push a way to externally update (not from discord) today

**Comment by nin0-dev** [comment]
okay issue is deeper than i thought

the patch for vencord settings above activity settings broke, which was the default until a while ago.

on top of all of that this patch will be disabled and replaced by the new default (above nitro).

**Comment by nin0-dev** [comment]
bugfix release will be made tomorrow, fixing this bug along with some others

sorry I've not been able to handle this earlier, i just had a lot of real life things to do

**Comment by nin0-dev** [comment]
okay I made release, you should see update alert in coming minutes

**Comment by Moodzz1** [comment]
Works, thanks 🫡

![Screenshot_2024-06-25-23-42-30-19_56bbc8167d0257d23a3582ded8ebec64](https://github.com/VendroidEnhanced/Vendroid/assets/88912716/faf6f44f-83e7-4dcf-8cba-6f0a330f1317)

**Comment by nin0-dev** [comment]
all good, however slash commands may not work, along with a DevTools experiment bar that may appear that'll block access to user settings and most of the chatbox

you may benefit from checking pinned issues before i release fixes in a few days
