### ISSUE TITLE
[Bug] <the theme discord+ doesn't work>

### ISSUE THREAD

**Issue by Sloom128** [VendroidEnhanced/Vendroid#56]
### Discord account

Sloom128

### What happens when the bug or crash occurs?

When you add a theme (downloading from the web and getting .CSS then adding it) it just makes the app unusable 

https://github.com/user-attachments/assets/eeae724f-efbb-4c50-9123-35156421885c

### What is the expected behaviour?

It should display the full app

### How do you recreate this bug or crash?

Add a theme. I think it doesn't affect other themes because I can't do anything, it just softlocks you

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
theme issue
