### ISSUE TITLE
[Bug] unable to join voice channel

### ISSUE THREAD

**Issue by Nyanpasu1** [VendroidEnhanced/Vendroid#67]
### What happens when the bug or crash occurs?

nothing happened when join vc clicked

### What is the expected behaviour?

should be able to voice call, tested on normal discord app and its working

### How do you recreate this bug or crash?

click one of voice channel and should be joined

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
if you had read the issue template you would’ve known this was a mobile web issue
