### ISSUE TITLE
[Bug] Forum channel posts are cut off at the sides

### ISSUE THREAD

**Issue by astra1dev** [VendroidEnhanced/Vendroid#69]
### What happens when the bug or crash occurs?

Open a forum channel, you will see it is cut off at the sides and you cant see the full post title. This happens in both gallery view and list view.

### What is the expected behaviour?

Open the forum channel normally and you can see every post clearly

### How do you recreate this bug or crash?

1. Open any forum channel
![d](https://github.com/user-attachments/assets/521edc3c-3c07-44cd-8a92-fab3a70232a2)

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by astra1dev** [comment]
I noticed this occurs aswell on discord web app w/o vencord. Sorry I didnt test before i opened the issue.

**Comment by nin0-dev** [comment]
at some point i’ll cook some CSS to fix these bugs
