### ISSUE TITLE
[Bug] Vendroid Settings not saving my Discord branch option.

### ISSUE THREAD

**Issue by slotmachinedev** [VendroidEnhanced/Vendroid#7]
### Discord account

needyakiraoverload

### What happens when the bug or crash occurs?

After hitting the Save button and relaunch Vendroid, my Discord branch option is not saved.
![Screenshot_20240429-224735_Vendroid](https://github.com/VendroidEnhanced/Vendroid/assets/166439659/5225a917-4974-44ea-a1b4-2fcd0a4a008c)

### What is the expected behaviour?

It should save my Discord branch option just fine.

### How do you recreate this bug or crash?

As title says, pretty straightforward:
1. Open Vendroid Settings;
2. Select a Discord branch (excluding Stable *for obvious reasons*);
3. Click Save;
4. Relaunch Vendroid.

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by slotmachinedev** [comment]
Oh, I see. Thanks for checking out the issue this fast!

**Comment by nin0-dev** [comment]
Fixed in most recent dev build
