### ISSUE TITLE
Everything out of you might be a CSS issue?

### ISSUE THREAD

**Issue by Tmonitor745** [VendroidEnhanced/Vendroid#79]
### Discord account

Tmonitor745

### What happens when the bug or crash occurs?

The app is kind of unusable with many elements being out of view
![Screenshot_2024-09-02_11-09-40](https://github.com/user-attachments/assets/565ac0e0-04e9-48b4-b7b1-038a5241aa2b)

### What is the expected behaviour?

Everything should be accessible

### How do you recreate this bug or crash?

Simply open vendroid even without patches

### Request agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
holy shit what did discord cook

fixing that soon

**Comment by nin0-dev** [comment]
also, does that happen with UI elements beyond the settings screen?

**Comment by Tmonitor745** [comment]
> also, does that happen with UI elements beyond the settings screen?

Yes all elements

**Comment by nin0-dev** [comment]
can't reproduce, either on AVD or on a testing device

whats your device model?

**Comment by nin0-dev** [comment]
closing because noone can reproduce and you haven’t been replying
