### ISSUE TITLE
v1.5 release is still 1.4 internally

### ISSUE THREAD

**Issue by Terrance** [VendroidEnhanced/Vendroid#80]
https://github.com/VendroidEnhanced/Vendroid/blob/9e3dbf24701ce9dbe366a133ceb94c8cdb24544c/app/build.gradle#L15

This means automatic updaters like Obtainium are constantly trying to update the app, because the version listed in GitHub releases is higher than the resulting downloaded APK.

**Comment by nin0-dev** [comment]
for some reason i bumped version number but not this string

fixing tonight

**Comment by nin0-dev** [comment]
thanks for reporting that oversight, i just bumped the version name

**Comment by Terrance** [comment]
All good now, thanks!
