### ISSUE TITLE
[FeatReq] Proposal for new icon.

### ISSUE THREAD

**Issue by CrimsonFork** [VendroidEnhanced/Vendroid#87]
### Feature description

The original icon is a bit thrown together and a bit inconsistent, so We remade it as pixel art at a base of 64x64 with different variations.
![vendroid-enhanced](https://github.com/user-attachments/assets/2f98f027-01c6-4bbd-8460-e7a90a9a0fd8)
![vendroid-enhanced-alt](https://github.com/user-attachments/assets/01c65933-f89e-4c3c-aaac-edda42a0982e)
![vendroid-enhanced-monochrome](https://github.com/user-attachments/assets/a371938a-1960-42bc-9747-65273bba607a)
[vendroid-enhanced-logo-proposal.zip](https://github.com/user-attachments/files/17153253/vendroid-enhanced-logo-proposal.zip)

### Request agreement

- [X] I am not suggesting a feature that could be selfbotting (automating/bulk sending actions)
- [X] I have checked for duplicates in the repo

**Comment by nin0-dev** [comment]
this looks great, I'll take a look later!
