### ISSUE TITLE
[FeatReq] replace vencord with equicord

### ISSUE THREAD

**Issue by Chaython** [VendroidEnhanced/Vendroid#88]
### Feature description
https://github.com/Equicord/Equicord
Equicord has significantly more extensions and is more active than vencord

### Request agreement

- [X] I am not suggesting a feature that could be selfbotting (automating/bulk sending actions)
- [X] I have checked for duplicates in the repo

**Comment by nin0-dev** [comment]
equicord will be added as an option, but it definitely won't replace vencord

**Comment by nin0-dev** [comment]
added in newest release!
