### ISSUE TITLE
invalid discord invite

### ISSUE THREAD

**Issue by 3SSF** [VendroidEnhanced/Vendroid#93]
### Discord account

lexintrus

### What happens when the bug or crash occurs?

i uhhh, well as stated the invite link is invalid

### What is the expected behaviour?

the invite link should work and let me join

### How do you recreate this bug or crash?

1. click invite
2. get redirected
3. wuh oh!!

on a serious note, i am sorry for using a bug report but this is the most suitable issue type i found

### Request agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [x] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
https://discord.gg/amjBZqdnqN
