### ISSUE TITLE
[FeatReq] idk

### ISSUE THREAD

**Issue by YashSoPro** [VendroidEnhanced/Vendroid#94]
### Feature description

you should make it smooth while using it takes alot of time to respond and definetly looks like web app and looks weird i know its web app that injects vencord but as its called vendroid enhancement so make it fast

also actively develop it

### Request agreement

- [x] I am not suggesting a feature that could be selfbotting (automating/bulk sending actions)
- [x] I have checked for duplicates in the repo

**Comment by nin0-dev** [comment]
smoothness is out of my control, if its bad on your phone chances are discordRN will be worse lmao

just use aliucord if u need something blazing fast

**Comment by YashSoPro** [comment]
> smoothness is out of my control, if its bad on your phone chances are discordRN will be worse lmao
> 
> just use aliucord if u need something blazing fast

i know its not on your control but doing some css tweaks etc can atleast make ui better sometimes text goes out of screen etc etc if u understand

**Comment by nin0-dev** [comment]
this is planned
