### ISSUE TITLE
[Bug] settings not showing

### ISSUE THREAD

**Issue by YashSoPro** [VendroidEnhanced/Vendroid#95]
### Discord account

SableMeow

### What happens when the bug or crash occurs?

i tried dev build and normal build but in settings i don't see vencord section i tried re installing many times

### What is the expected behaviour?

when i installed dev build from actions and opened settings i did not see vencord section so i thought its dev that's why than i installed normal build from releases same thing happened i tried re installing many times im on stable version

### How do you recreate this bug or crash?

install
open vendroid
open settings
you will see vencord is missing

### Request agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [x] I have read the requirements for opening an issue above

**Comment by YashSoPro** [comment]
i don't know how i tried again now it works but yoiu can still look into it so it won't happen with other guys

**Comment by nin0-dev** [comment]
fixed in latest update
